### ISSUE TITLE
`utterances` is not installed on `etiennebacher/personal_website_distill`

### ISSUE THREAD

**Issue by vgherard** [etiennebacher/personal_website_distill#5]
Thought this might interest you.

![Screenshot_20210717_122645](https://user-images.githubusercontent.com/62836440/126034065-0f387606-c1ce-4f94-891d-4b28d7b9bdbc.png)

Cheers,
V

**Comment by vgherard** [comment]
The above screenshot is what I got trying to comment a blog post

**Comment by etiennebacher** [comment]
Thank you! I fixed it, please reopen if you still can't comment

**Comment by vgherard** [comment]
Everything works, thanks :)
